; Promicro + E22(0)-xxxM / HT-RA62 modules board variant - DIY - with TCXO
[env:nrf52_promicro_diy_tcxo_lr1121_1g9]
extends = nrf52840_base
board = promicro-nrf52840
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/nrf52_promicro_diy_tcxo_lr1121-1g9
  -D NRF52_PROMICRO_DIY
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/nrf52_promicro_diy_tcxo_lr1121-1g9>
lib_deps = 
  ${nrf52840_base.lib_deps}
debug_tool = jlink

; NRF52 ProMicro w/ E-Ink display
[env:nrf52_promicro_diy_lr1121_1g9-inkhud]
board_level = extra
extends = nrf52840_base, inkhud
board = promicro-nrf52840
build_flags =
  ${nrf52840_base.build_flags}
  ${inkhud.build_flags}
  -I variants/nrf52840/diy/nrf52_promicro_diy_tcxo_lr1121-1g9
  -D NRF52_PROMICRO_DIY
build_src_filter =
  ${nrf52_base.build_src_filter}
  ${inkhud.build_src_filter}
  +<../variants/nrf52840/diy/nrf52_promicro_diy_tcxo_lr1121-1g9>
lib_deps =
  ${inkhud.lib_deps} ; InkHUD libs first, so we get GFXRoot instead of AdafruitGFX
  ${nrf52840_base.lib_deps}
extra_scripts =
  ${env.extra_scripts}
  variants/nrf52840/diy/nrf52_promicro_diy_tcxo_lr1121-1g9/custom_build_tasks.py ; Add to PIO's Project Tasks pane: preset builds for common displays
